#!/bin/bash -ex

[ "$FAB_HTTP_PROXY" ] &&  http_proxy="$FAB_HTTP_PROXY"

REPO_URL=git://github.com/ushahidi
WEBROOT=/var/www/ushahidi

mkdir -p $WEBROOT

git clone --depth 1 $REPO_URL/Ushahidi_Web.git $WEBROOT

rm -rf $WEBROOT/application/i18n
mkdir -p $WEBROOT/application/i18n

git clone --depth 1 $REPO_URL/Ushahidi-Localizations.git $WEBROOT/application/i18n

