#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.7.4"
URL="https://github.com/ushahidi/Ushahidi_Web/archive/$VERSION.zip"
SRC=/usr/local/src

dl $URL $SRC
mv $SRC/$VERSION.zip $SRC/ushahidi.zip
