#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.6.1"
URL="http://cloud.github.com/downloads/ushahidi/Ushahidi_Web/Ushahidi_Web-$VERSION.zip"

dl $URL /usr/local/src

