#!/bin/sh -ex

DB_NAME=ushahidi
DB_USER=ushahidi
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/ushahidi

# set permissions
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/application/config
chown -R www-data:www-data $WEBROOT/application/cache
chown -R www-data:www-data $WEBROOT/application/logs
chown -R www-data:www-data $WEBROOT/media/uploads
chown www-data:www-data $WEBROOT/.htaccess

# configure apache
a2dissite 000-default
a2ensite ushahidi
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
URL="http://127.0.0.1/installer/"
CURL="curl -c /tmp/cookie -b /tmp/cookie"
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)

$CURL $URL --data "install_mode_basic=1"
$CURL $URL --data "continue=Let%27s+get+started%21"
$CURL $URL --data "database=$DB_NAME&username=$DB_USER&password=$DB_PASS&host=localhost&table_prefix=&connection=&permission=&load_db_tpl=&load_htaccess_file=&config_perm=&htaccess_perm=&continue=Continue+%E2%86%92"
$CURL $URL --data "site_name=TurnKey+Ushahidi&site_tagline=Crowdsourcing+information&site_language=en_US&site_email=$EMAIL&enable_clean_urls=1&continue=Continue+%E2%86%92"
$CURL $URL --data "email=$EMAIL&password=$ADMIN_PASS&confirm_password=$ADMIN_PASS&continue=Continue+%E2%86%92"

rm -f /tmp/cookie

# work around issues when running under php5.4: "Non-static method xxxx::xxxx() should not be called statically"
sed -i 's|error_reporting(E_ALL \& ~E_STRICT);|error_reporting(E_ALL \& ~E_STRICT \& ~E_DEPRECATD);|' /var/www/ushahidi/index.php

# tweak configuration (compression)
CONF=$WEBROOT/application/config/config.php
sed -i "s|output_compression'\].*|output_compression'\] = FALSE;|" $CONF

# secure sensitive configuration files
chmod 640 $WEBROOT/application/config/config.php
chmod 640 $WEBROOT/application/config/encryption.php
chmod 640 $WEBROOT/application/config/database.php

# delete installation
rm -rf $WEBROOT/installer

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

