#!/bin/bash -e
# regenerate ushahidi secrets and mysql password

. /etc/default/inithooks

WEBROOT=/var/www/ushahidi
CONF=$WEBROOT/platform/.env
DB_PASS=$(mcookie)

sed -i "\|^APP_KEY=|s|=.*|=$(mcookie)|" $CONF
sed -i "\|^DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ushahidi --pass="$DB_PASS"

OATH_DIR=$WEBROOT/platform/storage/passport
rm -rf $OATH_DIR
mkdir -p $OATH_DIR
cd $WEBROOT/platform
php artisan passport:keys
