#!/bin/bash -e
# regenerate ushahidi secrets and mysql password

. /etc/default/inithooks

CONF_DIR=/var/www/ushahidi/application/config

CONF=$CONF_DIR/encryption.php
sed -i "s|\['key'\].*|\['key'\] = '$(mcookie)';|" $CONF

CONF=$CONF_DIR/database.php
PASSWORD=$(mcookie)
sed -i "s|'pass'.*|'pass'     => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ushahidi --pass="$PASSWORD"

